config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :posts
  resources :properties
  devise_for :accounts

  get "/blog" => "posts#latest", as: :blog
  #admin routes
  get "/accounts" => 'admin#accounts', as: :accounts

  get '/dashboard' => 'dashboard#index', as: :dashboard
  get '/profile/:id' => 'dashboard#profile', as: :profile
  post "/agent/message" => "properties#email_agent", as: :email_agent

  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord
    belongs_to :account

    # Function that adds a meeting to a given calendar
    def add_meeting_to_calendar(calendar_id, service)
        service = Calendar.init_service 
        event_id = "meeting#{id}"
        meeting_name = name
        event = Calendar.create_event(meeting_name, start_time, end_time + 1.day, event_id)
        # begin
        puts "Event is #{event}"
        service.insert_event(calendar_id, event)
        # rescue Google::Apis::ClientError => e
        # if e.status_code == 409
        #     # We are ignoring the case when adding a user back to a team
        #     puts 'Google API detected duplicate event id, ignoring'
        # else
        #     raise
        # end
        # end
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]
  before_action :can_access?

  def can_access?
    @show_sidebar = true
    
  end
  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.where(account_id: current_account.id)
  end

  # GET /meetings/1 or /meetings/1.json
  def show
    start_date = params.fetch(:start_time, Date.today).to_date
    @meetings = Meeting.where(account_id: current_account.id)
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.account_id = current_account.id
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save meeting",class: "btn btn-success"%>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1 class="h3">Meetings</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time.in_time_zone("Bucharest").strftime("Date: %F Time: %T") %></td>
        <td><%= meeting.end_time.in_time_zone("Bucharest").strftime("Date: %F Time: %T") %></td>
        <td><%= link_to 'Show', meeting, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting), class: "btn btn-success" %></td>
        <td><%= button_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path, class: "btn btn-success" %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>


<%= month_calendar events: @meetings do |date, meetings| %>
    <%= date.day %>
    <% meetings.each do |meeting| %>
    <div>
      <%= meeting.name %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>